### ISSUE TITLE
Reusage of old sessions

### ISSUE THREAD

**Issue by voruti** [LReg/PlanningPoker#2]
When trying to join using an old session link, that won't work.

I would like to be able to reuse old sessions, so I don't have to create new ones everytime I want to use the app.

Possible implementation options would be:
* adding a database to persist the session
* saving the sessions in the browser and recreating the session with that information
* don't save anything and transparently create a new session on the fly

**Comment by LReg** [comment]
- "don't save anything and transparently create a new session on the fly" this seems like the best way to me
- maye if session you join no longer exists ask with a modal if you want to recreate a new session with the same name
- tho the joining of other player wont really work that way
- maybe you can change the creation progress so you can reuse session tokens
- then the join links would not totally be invalid
- some audit needs to be done before starting this ticket
